### ISSUE TITLE
[Feature Request]: macOS 13 support for Vanilla Installer itself

### ISSUE THREAD

**Issue by Kichura** [Fabulously-Optimized/vanilla-installer#125]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Potential Enhancement

GitHub has released a beta testing image of macOS 13 for all action users where they can test out the newest software in this operating system as macOS 12 is fully functional with our software already.

[The source itself for reference,](https://github.blog/changelog/2023-04-24-github-actions-macos-13-is-now-available)
[The issue commenting about it although likely outdated.](https://github.com/actions/runner-images/issues/6426)

### How it could be implemented

To make use of it, Test-Swap the "macos-12" statement with "macos-13" in the `ci.yml` workflow script itself.

### Anything else?

When using the macos-13 statement itself, expect issues to happen as the image is unfinished and requires fixes to compile vanilla installer itself properly, another thing to note is that there is no documentation about it at this time meaning we must go in blind for this one at time of writing this """issue""",

And another thing to note is that any image containing `-xl` at the end of their names indicate the same images but improved ones and that those require a subscription to work in first place.

**Comment by Kichura** [comment]
Update: The [README](https://github.com/actions/runner-images/blob/main/images/macos/macos-13-Readme.md) documentation for macOS 13 has been released.

**Comment by osfanbuff63** [comment]
Notably, macOS 13 doesn't have Python preinstalled, so it might take a bit longer to execute.

(Right now, looks like ~30s more - doesn't matter much though)
