### ISSUE TITLE
Should we implement "Sentry"? If so, should we enable it by default?

### ISSUE THREAD

**Issue by nsde** [Fabulously-Optimized/vanilla-installer#14]
I think the Vanilla Installer might crash often, as it's in the alpha developement stage right now.

Should we log crash reports to improve our software? Opt-in or opt-out?
Sentry is an open source tool for that: https://github.com/getsentry/sentry
Should we use it? It seems to have a nice dashboard.

***

My opinion:
We start with opt-out (not hidden in submenus or anything).
The more stable this project gets, the more we can care about privacy.

When the project is in the beta stage, we can set it to opt-in.

**Comment by Madis0** [comment]
Perhaps a dumb question, but what part of this can actually "crash"? It seems more likely users will just get errors, which can be logged but not all of them should be directly sent somewhere.

**Comment by osfanbuff63** [comment]
> Perhaps a dumb question, but what part of this can actually "crash"? It seems more likely users will just get errors, which can be logged but not all of them should be directly sent somewhere.

There's cases where it might hang, but I couldn't actually find a `sys.exit` in the main.py, which is interesting. It's probably worth implementing some exits in cases where we know it'll fail, if we run into them.

**Comment by Madis0** [comment]
Right. Well, currently I am **against** this idea and would rather suggest making it really easy for users to report this stuff (stack trace + version/system data templates, direct links to GitHub and Discord). 
Can be reconsidered later if there still seems to be a need for this.

**Comment by nsde** [comment]
> what part of this can actually "crash"?

Oh, I think I have expressed incorrectly. I mean errors in general.

**Comment by nsde** [comment]
> I am **against** this idea and would rather suggest making it really easy for users to report this stuff

Okay! I'm OK with your choice since I was also unsure. But I agree with your point that we should make error reporting easier. I can do this.
