### ISSUE TITLE
Why do we have four Python version folders (3.8, 3.9, 3.10, 3.11) in the root directory?

### ISSUE THREAD

**Issue by nsde** [Fabulously-Optimized/vanilla-installer#15]
@osfanbuff63 what are these folders used for?
I think we should put them in a separate directory.

**Comment by nsde** [comment]
![image](https://user-images.githubusercontent.com/67185896/195374663-f0386968-7b38-46fb-adb0-44174c55d233.png)

**Comment by osfanbuff63** [comment]
Already changed this locally, it's for [pipenv](https://docs.pipenv.org). They're being moved to an envs folder, but I just haven't pushed the commit.

Basically - it would make our life easier if we only supported one Python version when installed locally or with scripts.

**Comment by nsde** [comment]
> it would make our life easier if we only supported one Python version

That's not an option. But alright.

**Comment by nsde** [comment]
@osfanbuff63 
Thanks for re-organizing the folders. Just a reminder: keep in mind not to change too many folders etc. at once in a fast time period, as this can be confusing if others are working on the project.
