### ISSUE TITLE
Issue templates

### ISSUE THREAD

**Issue by osfanbuff63** [Fabulously-Optimized/vanilla-installer#17]
Preferably in the format of [issue forms](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-issue-forms), just to make our life a bit easier when it comes to feature requests and bug reports.

**Comment by nsde** [comment]
:+1: Great idea!

**Comment by nsde** [comment]
Thanks, @osfanbuff63 !

**Comment by osfanbuff63** [comment]
No problem! Are there any other issue templates you think we should make, or am I good to close this issue?

**Comment by nsde** [comment]
I don't know.

**Comment by osfanbuff63** [comment]
Alright, going to mark this as completed now. Go ahead and make a new meta issue if you think of one to add.
