### ISSUE TITLE
Fix Pylint / add pylint.toml

### ISSUE THREAD

**Issue by nsde** [Fabulously-Optimized/vanilla-installer#19]
Anyone want to help me getting the PyLint actions to work?

![image](https://user-images.githubusercontent.com/67185896/195446157-e7433485-a56b-4632-99b9-1c573cca3c07.png)

**Comment by osfanbuff63** [comment]
If you want to take a shot at it, feel free - I've been fighting with this thing for a few days now, and just kinda gave up eventually lol

**Comment by nsde** [comment]
ok!

**Comment by osfanbuff63** [comment]
With #36, the CI doesn't use pylint specifically, so this issue won't be relevant anymore once that PR is merged.

**Comment by osfanbuff63** [comment]
^
