### ISSUE TITLE
[Feature Request]: Design proposal 

### ISSUE THREAD

**Issue by tuxinal** [Fabulously-Optimized/vanilla-installer#28]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Potential Enhancement

The current UI isn't the best and [a rewrite is planned](https://github.com/Fabulously-Optimized/vanilla-installer/blob/7447eb7b423e64fff896fc4cee657e1e7cafde3d/docs/planned-features.md) anyways
I have thrown together a design and I'd like to see what you think of it

### How it could be implemented

light mode:
![](https://cdn.discordapp.com/attachments/859124104644788237/1032339332343803925/unknown.png)
dark mode:
![](https://cdn.discordapp.com/attachments/859124104644788237/1032339476191657984/unknown.png)

Figma link: https://www.figma.com/file/KmhApEpUavYCJBSqBUnXbh/FO-Vanilla-installer

**Comment by Madis0** [comment]
I would make the path a textbox/folder picker right away, like in Fabric installer.
And what is the exclamation mark in the bottom left?

**Comment by tuxinal** [comment]
The exclamation mark is the "Info" button in the current UI
I probably should've actually considered what the UI needs instead of just redesigning the current UI

**Comment by osfanbuff63** [comment]
Even if we end up revising the design a bit, this is worth a mention for sure.

**Comment by tuxinal** [comment]
Here is the current design:
![image](https://user-images.githubusercontent.com/24763016/197125308-2d1de0ba-2ba3-483d-9c13-dc2d0d7002b5.png)
![image](https://user-images.githubusercontent.com/24763016/197125387-f556a712-6595-42e2-90c8-f2bbd03077b3.png)

I am preparing a pr for this so if you have any changes in mind please let me know

**Comment by Madis0** [comment]
Looks good, except that exclamation mark still bothers me :grin: 
I don't know, should it be an About button? Or a  :information_source: icon maybe? Not something critical at least.

**Comment by tuxinal** [comment]
replaced it with a github icon, as it links to the repo in the current GUI

![image](https://user-images.githubusercontent.com/24763016/197130637-5672ee9c-29a5-4b51-9c8b-c1d31ee9ff2f.png)

**Comment by nsde** [comment]
> The exclamation mark is the "Info" button in the current UI
> I probably should've actually considered what the UI needs instead of just redesigning the current UI

We could also add an bug report button 🪲
