### ISSUE TITLE
[Meta]: Add actual repo description (hope this is the correct label)

### ISSUE THREAD

**Issue by nsde** [Fabulously-Optimized/vanilla-installer#34]
@Madis0 please add an actual repository description instead of "Soon" :)

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by Madis0** [comment]
Done. Feel free to suggest more topics below it.

**Comment by osfanbuff63** [comment]
Probably `minecraft` and `fabric`/`fabricmc`, off the top of my head.

**Comment by Madis0** [comment]
Should be enough now I guess.

**Comment by osfanbuff63** [comment]
Alright, I'll close this for now. If you have anything else @nsde, feel free to comment :P
