### ISSUE TITLE
[Feature Request]: Version file

### ISSUE THREAD

**Issue by Madis0** [Fabulously-Optimized/vanilla-installer#35]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Potential Enhancement

Let's say 1.19.3 comes out tomorrow. How would I add this to the installer? There needs to be a really easy way to manage these versions.

### How it could be implemented

I would prefer a single file of name-link mapping, e.g.

```
{
   "1.16.5": "https://example.com/1.16.5/pack.toml",    
   "1.17.1": "https://example.com/1.17.1/pack.toml",   
   "1.18.2": "https://example.com/1.18.2/pack.toml",
   "1.19.3": "https://example.com/1.19.3/pack.toml"
}
```

The installer would simply ping that file on every launch to get the latest info, no installer updates are needed.

**Comment by nsde** [comment]
Okay, where should the mapping file be located?

**Comment by Madis0** [comment]
In `envs` folder maybe? Just somewhere in this repo, not included with the download.

**Comment by tuxinal** [comment]
currently the installer takes the versions from the packwiz folder on the main repo using the github api so it's all automated: https://github.com/Fabulously-Optimized/vanilla-installer/blob/5df7663611371e1fa1ee3457448c6d4c248e4755/vanilla-installer/main.py#L319-L340

unless i'm misunderstanding something

**Comment by Madis0** [comment]
Hmm... On one hand, this automation is cool, on the other hand I don't want more people using 1.19 than there are now, aka I would still prefer to have a subset of these folders that are displayed in the installer.

Edit: some kind of "default" should also be a thing. For cases where the latest version is not stable yet, it should not be selected by default.

**Comment by tuxinal** [comment]
Those are good points and this would also let us not need to use github's api anymore.

**Comment by nsde** [comment]
> I don't want more people using 1.19 than there are now

Sorry, I don't understand what you mean.

**Comment by osfanbuff63** [comment]
To sum it up, we (being FO) don't support or recommend 1.19(.0) even though it doesn't have chat reporting since we have NCR - so we shouldn't encourage users to install the 1.19(.0) version in VI.
