### ISSUE TITLE
[Feature Request]: exe binary/build for Windows

### ISSUE THREAD

**Issue by nsde** [Fabulously-Optimized/vanilla-installer#38]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Potential Enhancement

Export this project as an `.exe` and publish to /releases tab

### How it could be implemented

https://pypi.org/project/auto-py-to-exe/

**Comment by nsde** [comment]
@osfanbuff63 When is the project expected to be ready?

**Comment by nsde** [comment]
When is it ready to be released

**Comment by osfanbuff63** [comment]
Depends on some more packaging things I'm working on locally (specifically Linux packaging), and how fast we can get issues like #35, #37, and #27 done - specifically #37 is blocking a release at a minimum, and then various packaging stuff like this and what I mentioned above.

**Comment by osfanbuff63** [comment]
Oh, and ideally we'll get @RaptaG to update the scripts, although I *might* be able to do it in a pinch (but I'm not that experienced with bash scripts lol)
~~maybe a powershell script for windows too idk~~

**Comment by RaptaG** [comment]
> Oh, and ideally we'll get @RaptaG to update the scripts, although I _might_ be able to do it in a pinch (but I'm not that experienced with bash scripts lol) ~maybe a powershell script for windows too idk~

Yeah, I can update the Linux/Mac scripts (I have to)

**Comment by osfanbuff63** [comment]
Also, I've recently been compiling with [cx-Freeze](https://pypi.org/project/cx-Freeze) because for some reason, the GUI doesn't compile correctly under pyinstaller for some reason. In theory, the CLI could be compiled with pyinstaller, but at that point why would we use 2 different compilers :P

The downside of that is we'd have to distribute as a zip file instead of just one file, but it's not a very cluttered zip file (3 or 4 files, not counting the exe) so I don't think that's a problem. macOS app bundles should also be easy with this. Linux is harder, since every single distro uses a different format :P (still thinking about that, and besides the issues already open, that's the biggest roadblock I think).

**Comment by nsde** [comment]
> Linux is harder, since every single distro uses a different format

Why don't we just use `pip` for that? Most Linux users know what they're doing, and Python comes pre-installed with many Linux distributions, too!

**Comment by osfanbuff63** [comment]
It's probably worth a thought at least. Thinking of trying to cater to Steam Deck users as well (as people running Linux on that are probably the least experienced Linux users, since it comes pre-installed there), but ultimately I think it'll just serve as a frontend to pip lol

**Comment by RaptaG** [comment]
> Why don't we just use `pip` for that? Most Linux users know what they're doing, and Python comes pre-installed with many Linux distributions, too!

:sweat_smile: https://github.com/Fabulously-Optimized/vanilla-installer/blob/b7a143ae50b7b612cc0b49379d140a5f36a7d6c0/install/linux.sh#L20

**Comment by osfanbuff63** [comment]
> > Why don't we just use `pip` for that? Most Linux users know what they're doing, and Python comes pre-installed with many Linux distributions, too!
> 
> 😅
> 
> https://github.com/Fabulously-Optimized/vanilla-installer/blob/b7a143ae50b7b612cc0b49379d140a5f36a7d6c0/install/linux.sh#L20

:P
With the scripts, you might just want to git clone anyway as a plus to them is you can use them on non-stable builds, however I believe pip can do this (`pip install git+https://github.com/Fabulously-Optimized/vanilla-installer`) but not sure if it could build it or not with poetry.

**Comment by osfanbuff63** [comment]
Given that we have some stuff with Windows builds out now, I'm going to close this.
