### ISSUE TITLE
[Feature Request]: Versioning and Changelogs

### ISSUE THREAD

**Issue by nsde** [Fabulously-Optimized/vanilla-installer#39]
### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### Potential Enhancement

For better organization etc.

### How it could be implemented

We should add a version code to our (pre-)releases and a `CHANGELOG.md`

**Comment by osfanbuff63** [comment]
Changelogs would currently be in `docs/changelogs/`, but I guess I could make a changelog.md that just links to the latest one. (That system was inspired by [Iris](https://github.com/IrisShaders/Iris/tree/trunk/docs/changelogs)'s system). On the versioning front, it probably makes sense to follow [PEP 440](https://peps.python.org/pep-0440/)'s system, as this is what's recommended for Python projects.

Prereleases are specifically [covered by PEP 440](https://peps.python.org/pep-0440/#pre-releases).

**Comment by osfanbuff63** [comment]
Created a [`CHANGELOG.md`](../blob/main/CHANGELOG.md) that just links to the current changelog on the wiki. Versioning as mentioned above will follow PEP 440 as there's really no reason to use anything else IMO when a) it's recommended and b) it's all that poetry supports...lol

Going to go ahead and close this so we can get closer to a beta (which I think will be potentially *very* soon).
