### ISSUE TITLE
[Bug]: Font won't apply immediately

### ISSUE THREAD

**Issue by Madis0** [Fabulously-Optimized/vanilla-installer#53]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

The font won't apply immediately:

![Font not applying](https://github.com/Fabulously-Optimized/vanilla-installer/raw/main/media/broken_font.png)

The workaround is to switch the theme twice (it works to just do it once but if you click the button twice you get the same theme).

![Font applied](https://github.com/Fabulously-Optimized/vanilla-installer/raw/main/media/normal_font.png)

### Version

Beta release

### What platform are you using?

Windows, macOS, Linux

### How did you download the software?

GitHub Releases

**Comment by nsde** [comment]
Same here.

![image](https://user-images.githubusercontent.com/67185896/210456771-93589fcd-8617-42b5-9173-1a0dab27f2d7.png)

**Comment by nsde** [comment]
After switching the theme twice, this font shows up:
![image](https://user-images.githubusercontent.com/67185896/210456808-c1bfd295-0379-43b6-86f5-f15b13695d24.png)

**Comment by osfanbuff63** [comment]
I can't spot the difference - I believe this is the intended font ([Inter](https://rsms.me/inter)) both times...?

**Comment by nsde** [comment]
![image](https://user-images.githubusercontent.com/67185896/210563334-b58c919a-8495-4c60-af77-b38df36d0754.png)
Here's both fonts layered on top. Let's just not load the font at all :joy:
It's just a few pixels

**Comment by tuxinal** [comment]
This didn't happen on Linux during when I was making the PR as long as Inter was installed correctly.
#46 _should_ fix this.
