### ISSUE TITLE
[Bug]: GUI is too big in size

### ISSUE THREAD

**Issue by Madis0** [Fabulously-Optimized/vanilla-installer#54]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

The GUI installer weighs 101MB. That's 4x the size of FO itself, and at least 10x the size of any average web-installer.

Please reduce the size by any means necessary, it shouldn't be larger than approx 10MB.

### Version

Beta release

### What platform are you using?

Windows

### How did you download the software?

GitHub Releases

**Comment by osfanbuff63** [comment]
This is unfortunately just the state of Python compiling. We have solutions that bundle the entire Python interpreter (`PyInstaller`, `cx_Freeze`, etc), or compiling it to C(++) and then compiling it to DLLs that way (`nuitka`). Both take up quite a lot of space; I think what's most at fault is the fact that we have to bundle Qt/PySide. *In theory* I could delete all the Qt DLLs that we don't use however I'm not sure how much that would help and if it would break anything.

The only other solution is a rewrite in another language that has a native compiler with a better solution - I think I was going to try to rewrite this in Rust to learn it and basically for fun; however if it ever is any better then we could consider using it. That's not in the scope of this *for now* though; not to mention I'm a terrible UI designer lol

**Comment by Madis0** [comment]
> We have solutions that bundle the entire Python interpreter (PyInstaller, cx_Freeze, etc), or compiling it to C(++) and then compiling it to DLLs that way (nuitka). Both take up quite a lot of space; I think what's most at fault is the fact that we have to bundle Qt/PySide. In theory I could delete all the Qt DLLs that we don't use 

Do test these options then.

Don't the style effects play any role in this? As in, using a system font/background and icons as normal buttons maybe could reduce the size.

**Comment by osfanbuff63** [comment]
Done some experimenting here - it turns out that when compiling we were including the `PySide6.examples` module, which is not used (as you could guess). Removing that brings it down to 31MB as a `.zip`, 21MB as a `.7z`, and 23MB as a onefile compressed exe. To say the least, that's progress.

**Comment by Madis0** [comment]
Could be even smaller but I'd say it is okay for the first release. 
Does zip really have to be 31 MB or can it be compressed more? Or more specifically, where is zip used/distributed, if at all?

**Comment by osfanbuff63** [comment]
> Or more specifically, where is zip used/distributed, if at all?

It isn't - it's just a test I did to just include the exe in a zip file or a 7z vs one file (made with `--onefile`) that extracts to a temp directory. I found it interesting that zip was that much more in testing though haha
