### ISSUE TITLE
[Bug]: Blank terminal window pops up on install

### ISSUE THREAD

**Issue by Madis0** [Fabulously-Optimized/vanilla-installer#58]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

Upon clicking the install button, a blank terminal window pops open. That doesn't seem necessary, just launch whatever you need from Python's OS commands.

### Version

Beta release

### What platform are you using?

Windows

### How did you download the software?

GitHub Releases

**Comment by osfanbuff63** [comment]
this doesn't happen with me, don't know what's happening here

**Comment by Madis0** [comment]
![image](https://user-images.githubusercontent.com/8611110/210418608-d7aaf20a-2369-48db-9324-0c206d42ffc5.png)

**Comment by osfanbuff63** [comment]
> ![image](https://user-images.githubusercontent.com/8611110/210418608-d7aaf20a-2369-48db-9324-0c206d42ffc5.png)

Oh...maybe it's using `java.exe` instead of `javaw.exe`? It's supposed to use javaw on Windows, but the underlying mll function could be getting that path instead somehow?

**Comment by Madis0** [comment]
![image](https://user-images.githubusercontent.com/8611110/210420376-57257ac0-d7ee-4530-a92b-d2e203e9a563.png)

(hovering on that tab)

**Comment by osfanbuff63** [comment]
https://gitlab.com/JakobDev/minecraft-launcher-lib/-/blob/master/minecraft_launcher_lib/utils.py#L89

Yeah, this doesn't get the path to javaw.exe (instead java.exe), so I'm going to have to change that section to being done manually.

**Comment by osfanbuff63** [comment]
This should be fixed in the next build.

**Comment by osfanbuff63** [comment]
Correction: This is fixed now, with the update to minecraft_launcher_lib. (I think I bumped that?)
