### ISSUE TITLE
[Bug]: Install button can be clicked during the install

### ISSUE THREAD

**Issue by Madis0** [Fabulously-Optimized/vanilla-installer#59]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

Once install button has been clicked, users should not be able to click it again until the install has completed.

### Version

Beta release

### How did you download the software?

GitHub Releases

**Comment by tuxinal** [comment]
Technically there is already a check that prevents the install process running multiple times. but i agree, it would be nicer if the button was disabled entirely.
