### ISSUE TITLE
[Bug]: Long versions are unreadable

### ISSUE THREAD

**Issue by Madis0** [Fabulously-Optimized/vanilla-installer#62]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

![image](https://user-images.githubusercontent.com/8611110/210419541-397e526d-23e5-4b57-9c29-7409b7f19511.png)

Make the dropdown a bit wider 🙂 

### Version

Beta release

### What platform are you using?

Windows

### How did you download the software?

GitHub Releases

### Additional data and screenshots

#56

**Comment by osfanbuff63** [comment]
Noticed this as well ~~- once you select 1.19.3 it renders fine it seems.~~

Correction: This is related to #53, because the same workaround for that works there.

**Comment by Madis0** [comment]
Kinda, but not fully as it is still too small after the selection.
![image](https://user-images.githubusercontent.com/8611110/210421375-3bb8585c-35c3-4e11-a694-0a63260485b5.png)
