### ISSUE TITLE
[Feature Request]: Prevent "Modpack is already up to date!"

### ISSUE THREAD

**Issue by Madis0** [Fabulously-Optimized/vanilla-installer#78]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Potential Enhancement

This window pops up by packwiz when the modpack VI is installing is apparently already up to date
![image](https://user-images.githubusercontent.com/8611110/217622205-0ef68360-88c0-4896-a00c-ccaf0345ac06.png)
It is shown for 10 seconds, after which it closes automatically.

Can VI prevent showing it altogether?

### How it could be implemented

Some packwiz check to see if things are up to date? Check the folder hash?

The goal is to prevent the install before Packwiz even launches, so that the timer won't count down.

### Anything else?

Not a big deal but would be nice to have regardless

**Comment by osfanbuff63** [comment]
`packwiz-installer` has an option to hide the GUI altogether, which I had considered passing, or maybe as a configuration option? The output is logged to the console (which in turn is redirected to the log, or at least should be), so if we need the information from it we can just ask for the `logs/vanilla_installer.log`. (For some reason, that is being created in the parent directory, but I'm going to make an issue for that

Either way, this is likely possible without too much struggle, as we can probably use hashes to determine updates (say, hash `index.toml` or `pack.toml` and compare it to the saved version in the config file (maybe something like `debug.index_hash`?).

**Comment by comp500** [comment]
You can pass the `--timeout` flag to packwiz-installer to bypass the timeout. This does however mean that the user won't be able to reconfigure optional mods if the list of optional mods hasn't changed, unless they manage to click the button very quickly.

**Comment by osfanbuff63** [comment]
I don't think FO uses optional mods (at least on stable), so that will be a good fix as well. Thanks :heart:

**Comment by comp500** [comment]
If a pack doesn't have any optional mods, it won't bother waiting at all :)

**Comment by Madis0** [comment]
FYI 1.16.5 does currently have Hydrogen as an optional mod (because it needs exactly Java 8), but the purposes of VI I'd say automatic skipping is a good thing.

**Comment by osfanbuff63** [comment]
Well, this will at least prevent the original issue from occurring - you'll still be asked to configure optional mods on 1.16.5 if this is the first time installing it [to this directory], which IMO is a good thing - especially because we don't support 1.16.5 anymore 😅
