### ISSUE TITLE
[Feature Request]: Explanatory tooltip next to versions

### ISSUE THREAD

**Issue by Madis0** [Fabulously-Optimized/vanilla-installer#88]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Potential Enhancement

I want a `(?)` icon next to the version selector that would show a tooltip on hover. Click would take to current installation wiki (link to be changed later)

### How it could be implemented

The tooltip could show a help text along the lines of:

> Vanilla Installer allows easy installation of all _supported_ versions of Fabulously Optimized. For legacy versions, download the respective MultiMC version from CurseForge and unpack it manually.

**Comment by osfanbuff63** [comment]
What should this link to exactly? Locally I made this link to FO version support, but I'm not sure if that's the correct option or not.

**Comment by Madis0** [comment]
I meant [this page](https://fabulously-optimized.gitbook.io/vanilla-installer/installation) but your idea might be even better.
