### ISSUE TITLE
[Feature Request]: Scripts for *nix

### ISSUE THREAD

**Issue by Madis0** [Fabulously-Optimized/vanilla-installer#90]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Potential Enhancement

Linux currently has complicated instructions that expect the user to know their system well. MacOS has no instructions. Can these be solved with sh scripts?

### How it could be implemented

Create separate sh scripts that do everything the instructions say for:
- Ubuntu/Debian
- Fedora
- Arch
- macOS?

### Anything else?

Not sure how easy it would be to create a non-intrusive script for macOS. I think it does have Python preinstalled though...

**Comment by osfanbuff63** [comment]
We have some outdated scripts at the moment, but updating them would be needed. IIRC macOS does have Python installed, but I don't remember what version - if it's >=3.8 we *should* be good? However, I haven't tested the code on <3.10 in a while, so it's possible I used some syntax that isn't available there.
